

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Rashik@123
      MYSQL_DATABASE: jobportal
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    build:
      context: .
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - ./job_portal:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  mysql_data:
