# Generated by Django 5.1.4 on 2024-12-18 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_delete_customcreationform'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobVacancies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobTitle', models.CharField(max_length=255)),
                ('branchEmail', models.EmailField(max_length=254)),
                ('jobQualification', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('contactNumber', models.IntegerField()),
                ('applicationEmailUrl', models.EmailField(max_length=254)),
                ('jobSkill', models.TextField()),
                ('jobType', models.TextField()),
                ('jobSalary', models.IntegerField(choices=[(1, 'Below $20,000'), (2, '$20,000 - $50,000'), (3, 'Above $50,000')], default=1)),
                ('workingEnvironment', models.TextField(choices=[('Remote', 'Remote'), ('Onsite', 'Onsite'), ('Hybrid', 'Hybrid')], default='Remote', max_length=255)),
                ('shortDiscription', models.TextField()),
                ('jobCategory', models.CharField(max_length=255)),
                ('jobResposibility', models.CharField(max_length=255)),
                ('jobRequirement', models.TextField()),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
