# Generated by Django 5.1.4 on 2024-12-18 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_jobvacancies'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobvacancies',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
