# Generated by Django 5.1.4 on 2024-12-19 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_jobvacancies_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobvacancies',
            name='company',
            field=models.ImageField(blank=True, null=True, upload_to='company_logo'),
        ),
    ]
