# Generated by Django 5.1.4 on 2024-12-19 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_jobvacancies_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobvacancies',
            old_name='company',
            new_name='companyLogo',
        ),
    ]
