# Generated by Django 5.1.4 on 2024-12-19 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_rename_company_jobvacancies_companylogo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobvacancies',
            name='companyLogo',
            field=models.ImageField(blank=True, default='company_logo/default_logo.png', null=True, upload_to='company_logo'),
        ),
    ]
