# Generated by Django 5.1.4 on 2024-12-24 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_alter_chatmessage_options_alter_chatmessage_receiver_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['-date']},
        ),
    ]
