# Generated by Django 5.1.4 on 2024-12-26 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_alter_chatmessage_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobvacancies',
            name='host',
        ),
    ]
