# Generated by Django 5.1.4 on 2024-12-26 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_remove_jobvacancies_host'),
    ]

    operations = [
        migrations.DeleteModel(
            name='friend',
        ),
    ]
