# Generated by Django 5.1.4 on 2025-01-08 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0016_delete_friend'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobvacancies',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobvacancies',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
