# Generated by Django 5.1.4 on 2025-01-10 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0017_jobvacancies_latitude_jobvacancies_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobvacancies',
            name='jobCategory',
            field=models.TextField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Short Time', 'Short Time')], default='Full Time', max_length=255),
        ),
    ]
